/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_halo_redpacket_jnicall_Native */

#ifndef _Included_com_halo_redpacket_jnicall_Native
#define _Included_com_halo_redpacket_jnicall_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_halo_redpacket_jnicall_Native
 * Method:    initilize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_halo_redpacket_jnicall_Native_initilize
  (JNIEnv *, jobject);

/*
 * Class:     com_halo_redpacket_jnicall_Native
 * Method:    threadStart
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_halo_redpacket_jnicall_Native_threadStart
  (JNIEnv *, jobject);

/*
 * Class:     com_halo_redpacket_jnicall_Native
 * Method:    threadStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_halo_redpacket_jnicall_Native_threadStop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
